const assert = require('node:assert/strict')
const {PumpkinGame} = require('../src/pumpkin-game.js')
const advance = (g, n = 60) => { for (let i = 0; i < n; i++) g.step(0.05) }
const g = new PumpkinGame()
advance(g); assert.equal(g.state, 'waiting'); assert.equal(g.elapsed, 0)
g.track(true); advance(g, 20)
g.track(false); const entrance = g.elapsed; advance(g)
assert.equal(g.elapsed, entrance)
g.track(true); advance(g, 30); assert.equal(g.state, 'playing')
g.aim = 5; advance(g, 15); assert.ok(g.x <= 0.94 && g.x > 0.9)
assert.ok(g.shots.length > 0)
g.track(false)
const snapshot = JSON.stringify(g)
advance(g); assert.equal(JSON.stringify(g), snapshot)
g.track(true); g.track(true); assert.equal(g.state, 'playing')
assert.equal(g.pumpkins.length, 15)
g.pumpkins = [{id: 0, x: 0, y: 0.5}, {id: 1, x: 0.6, y: 1}]
g.offset = 0; g.shots = [{x: 0, y: 0.35}]; g.step(0.05)
assert.equal(g.score, 100); assert.equal(g.pumpkins.length, 1)
g.pumpkins = []; g.step(0.05)
assert.equal(g.wave, 2); assert.equal(g.pumpkins.length, 15)
g.offset = 0.359; g.direction = 1; g.step(0.05)
assert.equal(g.direction, -1); assert.ok(g.drop > 0)
for (let i = 0; i < 3; i++) { g.drop = 9; g.step(0.05) }
assert.equal(g.lives, 0); assert.equal(g.state, 'gameOver')
const end = JSON.stringify(g); advance(g); assert.equal(JSON.stringify(g), end)
g.track(false); g.reset(); assert.equal(g.state, 'waiting')
assert.equal(g.score, 0); assert.equal(g.lives, 3); assert.equal(g.wave, 1)
assert.equal(g.shots.length, 0); assert.equal(g.effects.length, 0)
g.track(true); advance(g, 50); g.reset(); assert.equal(g.state, 'owlEntrance')
advance(g, 5000); assert.ok(g.shots.length <= 12); assert.ok(g.effects.length <= 15)
console.log('PASS: waiting, entrance pause, controls, firing, collision, waves, breach, game over, replay, bounded objects')
